server:
  port: 8888
logging:
  level:
    root: info
spring:
  application:
      name: @artifactId@
# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

